import { z } from 'zod';
import type { AnswerMarker, CardAnswerV2, ExportEnvelopeV2, LegacyExpoProfile, LegacyV1Profile, Participation, ProfileV2, Stance } from '@/types';
import { CATEGORIES } from '@/data/categories';

export const MAX_IMPORT_CHARS = 500_000;
export const MAX_NOTE_CHARS = 10_000;
export const CONTENT_VERSION = 'v2.0.0';
const stanceValues = ['want', 'open', 'unsure', 'not_for_me', 'hard_limit'] as const;
const markerValues = ['important', 'future_possible', 'need_discussion'] as const;
const participationValues = ['self', 'other', 'together', 'varies'] as const;

const answerSchema = z.object({ cardId: z.string().min(1), stance: z.enum(stanceValues).optional(), markers: z.array(z.enum(markerValues)).max(3).optional(), participation: z.enum(participationValues).optional(), note: z.string().max(MAX_NOTE_CHARS).optional(), updatedAt: z.string().datetime(), legacy: z.object({ rawStatuses: z.array(z.string()), needsReview: z.boolean() }).optional() });
const profileSchema = z.object({ schemaVersion: z.literal(2), id: z.string().min(1), title: z.string().min(1), direction: z.object({ author: z.object({ id: z.string().min(1), displayName: z.string() }), subject: z.object({ id: z.string().min(1), displayName: z.string() }) }), relationLabels: z.array(z.string()), selectedCategoryIds: z.array(z.string()), answers: z.record(z.string(), z.object({ categoryId: z.string(), answers: z.record(z.string(), answerSchema), viewedCardIds: z.array(z.string()).optional() })), provenance: z.discriminatedUnion('kind', [z.object({ kind: z.literal('local') }), z.object({ kind: z.literal('imported'), sourceProfileId: z.string(), sourceExportId: z.string(), importedAt: z.string() }), z.object({ kind: z.literal('fork'), sourceProfileId: z.string(), sourceExportId: z.string().optional(), forkedAt: z.string() })]), permissions: z.object({ editable: z.boolean() }), contentVersion: z.string(), createdAt: z.string().datetime(), updatedAt: z.string().datetime(), legacy: z.object({ rawData: z.unknown(), unmappedItems: z.array(z.unknown()) }).optional() });
const envelopeSchema = z.object({ kind: z.literal('ra-smorgasbord-profile'), schemaVersion: z.literal(2), exportId: z.string().min(1), exportedAt: z.string().datetime(), contentVersion: z.string(), privacy: z.object({ includesNotes: z.boolean(), encoding: z.literal('base64'), encrypted: z.literal(false) }), profile: profileSchema, digest: z.string().min(1) });

export function makeId(): string { if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') return crypto.randomUUID(); return `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
export function describePerspective(authorName: string, subjectName: string): string { return `${authorName || '未填写'}填写了自己与${subjectName || '未填写'}的这段关系`; }
export function isAnswerEffective(answer: Partial<CardAnswerV2> | undefined): boolean { return Boolean(answer?.stance || answer?.participation || (answer?.markers?.length ?? 0) > 0 || answer?.note?.trim()); }
export type ComparisonKind = '相近' | '有所不同' | '值得聊聊' | '有人未回答' | '都有备注' | '需要阅读语境';
export function classifyComparison(answers: Array<Partial<CardAnswerV2> | undefined>): ComparisonKind {
  const effective = answers.filter(isAnswerEffective);
  if (effective.length < answers.length) return '有人未回答';
  if (answers.some(answer => answer?.markers?.includes('need_discussion') || answer?.stance === 'hard_limit')) return '值得聊聊';
  const noteOnly = (answer: Partial<CardAnswerV2> | undefined) => Boolean(answer?.note?.trim()) && !answer?.stance && !answer?.participation && !(answer?.markers?.length);
  if (answers.every(noteOnly)) return '都有备注';
  if (answers.some(noteOnly)) return '需要阅读语境';
  const stances = new Set(answers.map(answer => answer?.stance));
  const markers = new Set(answers.flatMap(answer => answer?.markers || []));
  const participation = new Set(answers.map(answer => answer?.participation));
  if (answers.every(answer => Boolean(answer?.note?.trim())) && (stances.size > 1 || markers.size > 1 || participation.size > 1)) return '需要阅读语境';
  return stances.size <= 1 && markers.size <= 1 && participation.size <= 1 ? '相近' : '有所不同';
}
export function normalizeAnswer(answer: CardAnswerV2): CardAnswerV2 | undefined { const normalized = { ...answer, note: answer.note?.trim() || undefined }; return isAnswerEffective(normalized) ? normalized : undefined; }
export function createProfile(title: string, authorName: string, subjectName: string, relationLabels: string[] = []): ProfileV2 { const now = new Date().toISOString(); return { schemaVersion: 2, id: makeId(), title: title.trim() || `${authorName} → ${subjectName}`, direction: { author: { id: makeId(), displayName: authorName.trim() }, subject: { id: makeId(), displayName: subjectName.trim() } }, relationLabels, selectedCategoryIds: [], answers: {}, provenance: { kind: 'local' }, permissions: { editable: true }, contentVersion: CONTENT_VERSION, createdAt: now, updatedAt: now }; }

export function migrateLegacyStatuses(rawStatuses: string[] = []): Pick<CardAnswerV2, 'stance' | 'markers' | 'participation' | 'legacy'> {
  const stances: Stance[] = []; const markers: AnswerMarker[] = []; const participations: Participation[] = []; let unknownStatus = false;
  const aliases: Record<string, string> = { yes: 'agree', required: 'necessary', maybe_future: 'future_possible', lets_talk: 'need_discussion', definitely_no: 'absolutely_not' };
  for (const rawValue of rawStatuses) { const raw = aliases[rawValue.trim()] || rawValue.trim(); if (raw === 'agree') stances.push('want'); else if (raw === 'will_do') participations.push('self'); else if (raw === 'maybe') stances.push('unsure'); else if (raw === 'absolutely_not') stances.push('not_for_me'); else if (raw === 'hard_limit') stances.push('hard_limit'); else if (raw === 'necessary') markers.push('important'); else if (raw === 'future_possible') markers.push('future_possible'); else if (raw === 'need_discussion') markers.push('need_discussion'); else if (raw === 'they_will') participations.push('other'); else if (raw === 'together') participations.push('together'); else if (raw === 'unwilling') stances.push('not_for_me'); else unknownStatus = true; }
  const uniqueStances = [...new Set(stances)]; const uniqueParticipations = [...new Set(participations)]; const needsReview = unknownStatus || uniqueStances.length > 1 || uniqueParticipations.length > 1 || (uniqueStances.includes('hard_limit') && markers.includes('important'));
  return { stance: uniqueStances[0], markers: [...new Set(markers)], participation: uniqueParticipations[0], legacy: rawStatuses.length ? { rawStatuses, needsReview } : undefined };
}

function migrateProgress(progress: LegacyV1Profile['progress'] = []) { const answers: ProfileV2['answers'] = {}; for (const category of progress || []) { const categoryAnswers: Record<string, CardAnswerV2> = {}; for (const old of category.answers || []) { const answer = normalizeAnswer({ cardId: old.cardId, ...migrateLegacyStatuses(old.statuses || []), note: old.note, updatedAt: new Date().toISOString() }); if (answer) categoryAnswers[old.cardId] = answer; } if (Object.keys(categoryAnswers).length) answers[category.categoryId] = { categoryId: category.categoryId, answers: categoryAnswers }; } return answers; }
export function migrateV1Profile(input: LegacyV1Profile): ProfileV2 { const now = new Date().toISOString(); const author = input.fromName?.trim() || ''; const subject = input.toName?.trim() || ''; return { schemaVersion: 2, id: makeId(), title: input.name?.trim() || `${author} → ${subject}`, direction: { author: { id: makeId(), displayName: author }, subject: { id: makeId(), displayName: subject } }, relationLabels: input.relationLabel ? [input.relationLabel] : [], selectedCategoryIds: [], answers: migrateProgress(input.progress), provenance: { kind: 'fork', sourceProfileId: input.id || 'legacy-v1', forkedAt: now }, permissions: { editable: true }, contentVersion: CONTENT_VERSION, createdAt: input.createdAt || now, updatedAt: input.updatedAt || now }; }
export function isLegacyExpoProfile(input: unknown): input is LegacyExpoProfile { if (!input || typeof input !== 'object') return false; const value = input as Record<string, unknown>; return typeof value.partnerName === 'string' && !('fromName' in value) && !('direction' in value); }
export function migrateExpoProfile(input: LegacyExpoProfile, authorName: string, subjectName: string): ProfileV2 { const profile = createProfile(`旧 Expo 档案：${authorName} → ${subjectName}`, authorName, subjectName); return { ...profile, provenance: { kind: 'fork', sourceProfileId: `legacy-expo-${input.timestamp || 'unknown'}`, forkedAt: new Date().toISOString() } }; }
export function validateProfile(input: unknown): ProfileV2 { const profile = profileSchema.parse(input); validateContentReferences(profile); return profile; }

function toBase64(value: string): string { const bytes = new TextEncoder().encode(value); let binary = ''; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary); }
function fromBase64(value: string): string { const binary = atob(value); const bytes = Uint8Array.from(binary, char => char.charCodeAt(0)); return new TextDecoder().decode(bytes); }
export function decodeLegacyBase64(value: string): string { const decoded = fromBase64(value); try { JSON.parse(decoded); return decoded; } catch { try { return decodeURIComponent(decoded); } catch { return decoded; } } }
export function parseLegacyExpoText(text: string): LegacyExpoProfile | null { try { const start = text.indexOf('---RAS_DATA_START---'); const end = text.indexOf('---RAS_DATA_END---'); const candidate = start >= 0 && end > start ? decodeLegacyBase64(text.slice(start + 20, end).trim()) : text.trim(); const parsed = JSON.parse(candidate) as unknown; if (isLegacyExpoProfile(parsed)) return parsed; if (parsed && typeof parsed === 'object' && 'profile' in parsed && isLegacyExpoProfile((parsed as { profile: unknown }).profile)) return (parsed as { profile: LegacyExpoProfile }).profile; } catch { /* handled by the confirmation UI */ } return null; }
export function digestString(value: string): string { let hash = 2166136261; for (let i = 0; i < value.length; i += 1) { hash ^= value.charCodeAt(i); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, '0'); }
export function createEnvelope(profile: ProfileV2, includesNotes = true): ExportEnvelopeV2 { const exportedProfile = includesNotes ? profile : stripNotes(profile); return { kind: 'ra-smorgasbord-profile', schemaVersion: 2, exportId: makeId(), exportedAt: new Date().toISOString(), contentVersion: profile.contentVersion, privacy: { includesNotes, encoding: 'base64', encrypted: false }, profile: exportedProfile, digest: digestString(JSON.stringify(exportedProfile)) }; }
function stripNotes(profile: ProfileV2): ProfileV2 { return { ...profile, answers: Object.fromEntries(Object.entries(profile.answers).map(([categoryId, category]) => [categoryId, { ...category, answers: Object.fromEntries(Object.entries(category.answers).map(([id, answer]) => [id, { ...answer, note: undefined }])) }])) }; }
export function encodeEnvelope(envelope: ExportEnvelopeV2): string { return toBase64(JSON.stringify(envelope)); }
export function validateContentReferences(profile: ProfileV2): void { const categories = new Map(CATEGORIES.map(category => [category.id, new Set(category.cards.map(card => card.id))])); for (const categoryId of profile.selectedCategoryIds) if (!categories.has(categoryId)) throw new Error(`导入档案包含未知类别：${categoryId}`); for (const [categoryId, progress] of Object.entries(profile.answers)) { const cardIds = categories.get(categoryId); if (!cardIds) throw new Error(`导入档案包含未知类别：${categoryId}`); for (const cardId of Object.keys(progress.answers)) if (!cardIds.has(cardId)) throw new Error(`导入档案包含未知卡片：${cardId}`); } }
export function decodeEnvelope(text: string): ExportEnvelopeV2 { if (text.length > MAX_IMPORT_CHARS) throw new Error('导入内容过大，请确认文件未被截断或包含无关内容。'); const start = text.indexOf('---RAS_DATA_START---'); const end = text.indexOf('---RAS_DATA_END---'); if (start < 0 || end < start) throw new Error('找不到可识别的机读区。'); let decoded: unknown; try { decoded = JSON.parse(decodeLegacyBase64(text.slice(start + 20, end).trim())); } catch { throw new Error('机读区损坏或不是有效的 Base64 JSON。'); } const parsed = envelopeSchema.parse(decoded); if (digestString(JSON.stringify(parsed.profile)) !== parsed.digest) throw new Error('导入摘要不一致，文件可能被修改或截断。'); validateContentReferences(parsed.profile); const answerCount = Object.values(parsed.profile.answers).reduce((sum, category) => sum + Object.keys(category.answers).length, 0); if (answerCount > 2000) throw new Error('回答数量超过安全上限。'); return parsed; }
